---
title: "LM030_MsIgMELISA_analysis"
author: "Libby Murphy"
date: "`r Sys.Date()`"
output: html_document
---

## setup
```{r setup, include=FALSE }
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library(drc)
library(tidyverse) 
library(ggthemes) 
library(gridExtra)
library(splitstackshape)
library(cowplot)
library(ggpubr)
library(here)
library(dplyr) 
```

```{r read in files and join, echo=FALSE}
#read in ELISA OD file and fix column names
ELISA <- read_csv(here("LM030", "LM030_OD450.csv")) 
colnames(ELISA)[2] <- "OD_450"

ELISA <- ELISA %>% 
  separate(
    col = Sample,
    into = c("Genotype", "treatment", "mouse"),
    sep = "_"
  ) 

ELISA$Genotype <- ELISA$Genotype %>%
  gsub(pattern = "blank", replacement = "stdH")

dplyr::filter(ELISA, OD_450 < 0)

ELISA <- ELISA %>%
  dplyr::filter(OD_450 > 0)

blank <- mean(ELISA %>%
  dplyr::filter(Genotype == "stdH") %>%
  pull(OD_450))
  
```


## ELISA model fit
```{r model fit, include=FALSE, , echo=FALSE}
#create object of just standards
standards <- ELISA %>% dplyr::filter(grepl("std", Genotype))

#create a tibble for the actual concentrations by std name
stdcrvdata <- data.frame(
    data.frame(Genotype = paste0("std",c("A","A","B","B","C","C","D","D","E","E","F","F","G","G","H","H")),
                 known = rep(c(1000,500,250,125,62.5,31.25,15.625,0),each=2))
  ) # <clown emoji>


# sort standards and stdcrvdata by name to match
standards <- standards %>% 
  arrange(Genotype) %>% 
  dplyr::select(c(Genotype,OD_450))

stdcrvdata <- stdcrvdata %>%
  arrange(Genotype)

# check if they are in the same order (I could change this to well location?)
stopifnot(identical((standards$Genotype), stdcrvdata$Genotype))

# combine them together
stdcrvdata <- data.frame(standards,expected=stdcrvdata$known)

stdcrvdata <- rename(stdcrvdata, measured = OD_450)

#remove std8 (blank std) because i'm about to take -log10 of all expected and -log10 of 0 is -inf, which is unplottable
stdcrvdata <- stdcrvdata %>% 
  filter(expected > 0)

#create a column in stdcrvdata with log10 known conc
stdcrvdata$logconc <-log10(stdcrvdata$expected)

# model the standard curve using generated points.  plot those points in red.
fit <- drm(formula =   measured ~ logconc , data = stdcrvdata, fct = LL.4()) # banana changed logconc to expected
summary(fit)

# This is a description of the variables and terms defined in the 'fit' model.
# x = the independent variable (Absorbance) (Concentration, estimated from the Absorbance)
# y = the dependent variable 
# The 4 estimated parameters consist of the following:

# the minimum value that can be obtained. (this is the ABS at conc. 0)
# a = fit$coefficients[2] 

# d = the maximum value that can be obtained (i.e. what happens at infinite dose)

# c = the point of inflection (i.e. the point on the S shaped curve halfway between a and d)

# b = Hill’s slope of the curve (i.e. this is related to the steepness of the curve at point c).

# Generate points from  model. Pick range from logconc
x <- seq(from = 0, to = 4, length=1000) 

# from OD ~ d + (a - d)/(1 + (logconc/cc)^b)
y <- (fit$coefficients[2]+ (fit$coefficients[3]- fit$coefficients[2])/(1+(x/fit$coefficients[4])^ fit$coefficients[1])) 
```

## Calculate IgM concentration from model
```{r calculate IgM conc, message=FALSE, warning=FALSE, echo=FALSE}
#create object with only measurements from experimental wells
OD <- ELISA %>% 
  filter(!grepl("std|nsb|NA", Genotype))

# subtract blank from OD_450
ELISA$OD_450 <- ELISA$OD_450 - blank

# here we are applying the equation described above to...
OD$loganswer<- fit$coefficients[4]*( # banana changed loganswer to answer
  (
    (-1* fit$coefficients[3]+ OD$OD_450)/
      (fit$coefficients[2]-OD$OD_450))^(1/ fit$coefficients[1])
  )

 OD$conc <- 10^OD$loganswer # banana commented out un-log transform bc answer is already natural
# OD$conc <- OD$answer # commented this out bc i think it's from the un-log process

OD$below <- OD$conc < min(stdcrvdata$expected)
OD$above <- OD$conc > max(stdcrvdata$expected)


plot(x = stdcrvdata$logconc, y = stdcrvdata$measured, main="log standard curve", # banana changed logconc to expected
  xlim = c(min(x),max(x)),
  ylim = c(min(y),max(y))
     ) 
  lines(x,y, lty="dotted", col="red") 
  lines(OD$loganswer, OD$OD_450, type="points", col="blue") # banana changed OD$loganswer to OD$answer
ggsave(plot = last_plot(), filename = "LM030_ME191_stdcrv.png", device = "png", path = here("LM030"))
# adjust concs for df
OD$adj <- OD$conc * 8

```

## Plots  
```{r echo=FALSE}

OD$treatment <- OD$treatment %>%
  factor(levels = c("DMEM", "H1N1"))
OD$Genotype <- OD$Genotype %>%
  factor(levels = c("WT", "MMP3KO"))


pWithOutlier <- ggplot(dplyr::filter(OD, Well != "C6"), aes(Genotype, adj)) +
  geom_boxplot(aes(fill = treatment)) +
  geom_point(position = position_dodge(width = 0.75), aes(group = treatment)) +
  geom_point(data = dplyr::filter(OD, Well == "C6"), position = position_dodge(width = 0.75), aes(x=Genotype, y=adj, group = treatment), color ="red") +
  theme_classic() +
  ggtitle("ME191: Ms IgM ELISA", subtitle = "WT H1N1 tx outlier pictured") 

pNoOutlier <- ggplot(dplyr::filter(OD, Well != "C6"), aes(Genotype, adj)) +
  geom_boxplot(aes(fill = treatment)) +
  geom_point(position = position_dodge(width = 0.75), aes(group = treatment)) +
  theme_classic() +
  ggtitle("ME191: Ms IgM ELISA", subtitle = "WT H1N1 tx outlier not pictured") 


  
ggsave(
  plot = pNoOutlier,
  filename = "LM030_ME191MsIgMELISA_nooutlier_plot.png",
  path = here::here("LM030"),
  device = "png",
  width = 6,
  height = 6
)

ggsave(
  plot = pWithOutlier,
  filename = "LM030_ME191MsIgMELISA_withoutlier_plot.png",
  path = here::here("LM030"),
  device = "png",
  width = 6,
  height = 6
)
```
