---
title: "LM037-1_ab287803_ELISA_analysis"
author: "Libby Murphy"
date: "`r Sys.Date()`"
output: html_document
---

## setup
```{r setup, include=FALSE }
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library(drc)
library(tidyverse) 
library(ggthemes) 
library(gridExtra)
library(splitstackshape)
library(cowplot)
library(ggpubr)
library(here)
library(dplyr) 
```

```{r read in files and prepare data, echo=FALSE}
#read in ELISA OD file and fix column names
ELISA <- read_csv(here("LM037", "LM037-1_ELISA_ab287803.csv")) [,c(2,4,5)]
colnames(ELISA) <- c("sample", "expected", "OD_450")

# dplyr::filter(ELISA, OD_450 < 0)
# ELISA <- ELISA %>%
#   dplyr::filter(OD_450 > 0)

#create object of just standards
stdcrvdata <- ELISA %>% 
  dplyr::filter(grepl("std", sample)) %>% 
  rename(measured = OD_450) %>% 
  filter(expected > 0) # This is because -log10(0) is not a number

#create object with only measurements from experimental wells
OD <- ELISA %>% 
  filter(sample != "empty") %>%
  filter(!grepl("std|nsb|NA", sample)) %>%
  group_by(sample) %>%
  summarise(OD_450 = mean(OD_450))

nsb <- ELISA[,c(1,3)] %>%
  filter(sample == "buffer")
```


## ELISA model fit
```{r model fit, include=FALSE, , echo=FALSE}
#create a column in stdcrvdata with log10 known conc
stdcrvdata$logconc <- log10(stdcrvdata$expected)

# model the standard curve using generated points.  plot those points in red.
fit <- drm(formula =   measured ~ logconc , data = stdcrvdata, fct = LL.4()) # banana changed logconc to expected
summary(fit)

# Generate points from  model. Pick range from logconc
x <- seq(from = 0, to = 4, length=1000) # banana changed 4 to 2000

# from OD ~ d + (a - d)/(1 + (logconc/cc)^b)
y <- (fit$coefficients[2]+ (fit$coefficients[3]- fit$coefficients[2])/(1+(x/fit$coefficients[4])^ fit$coefficients[1])) 
```

## Calculate HNE concentration from model
```{r calculate HNE conc, message=FALSE, warning=FALSE, echo=FALSE}
# subtract nsb from experimental wells
# OD$OD_450 <- OD$OD_450 - nsb$OD_450 # not really sure this is the right way to do this...will look it up banana

# here we are applying the equation described above to...
OD$loganswer<- fit$coefficients[4]*( # banana changed loganswer to answer
  (
    (-1* fit$coefficients[3]+ OD$OD_450)/
      (fit$coefficients[2]-OD$OD_450))^(1/ fit$coefficients[1])
  )

 OD$conc <- 10^OD$loganswer # banana commented out un-log transform bc answer is already natural
# OD$conc <- OD$answer # banana commented this out bc i think it's from the un-log process

OD$below <- OD$conc < min(stdcrvdata$expected)
OD$above <- OD$conc > max(stdcrvdata$expected)


plot(x = stdcrvdata$logconc, y = stdcrvdata$measured, main="log standard curve", # banana changed logconc to expected
  xlim = c(min(x),max(x)),
  ylim = c(min(y),max(y))
     )
lines(x,y, lty="dotted", col="red")
lines(OD$loganswer, OD$OD_450, type="points", col="blue") # banana changed OD$loganswer to OD$answer

```

## Plots  
```{r plots, echo=FALSE}
OD %>%
  ggplot() +
  geom_col(aes(x = sample, y = conc, fill = sample)) +
  theme_few() +
  ggtitle("LM037-1 ab287803 sad result womp womp")

ggsave(
  plot = f,
  filename = "20230815_HNE_ELISA_plots.png",
  path = here::here("LM018", "20230815_HNE_ELISA_plots.png"),
  device = "png",
  width = 8
)
```