---
title: "LM003_WBanalysis"
author: "Libby Murphy"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggthemes)
library(ggpubr)
library(dplyr)
library(here)
library(tidyverse)
library(reshape2)
library(ggsignif)
```

```{r definitions}
# Supply definitions. These names must exactly match the sample names in your band quant csvs, including capitalization.

nprobes <- 3 # how many genes did you probe for, including HKG? (aka number of images you took)

sample1 <- "unstim" #names of your lanes. what samples did you run on your gel? each replicate is its own sample. 
sample2 <- "min5"
sample3 <- "min15"
sample4 <- "min30"
sample5 <- "min60"
sample6 <- "min120"

HKG <- "ACTB" # gene symbol for your housekeeper. Other genes will be normalized to this
gene1 <- "SMAD3" # gene symbol of first gene you probed for other than HKG
gene2 <- "pSMAD3" # gene symbol of second gene you probed for other than HKG

exptName <- "LM003" # this should be the name of the folder that your data lives in. This is the folder that contains the sub-folder WBQuants.

plotTitle <- "LM003 pSMAD3/SMAD3 WB signals normalized to ACTB" # what do you want your plot to be titled?
```

```{r import CSVs, but this time not clown-style}
myfiles <- data.frame(
  files = list.files(path = here::here(exptName), full.names = TRUE, recursive = TRUE, all.files = FALSE)
) %>%
  dplyr::filter(
    grepl(
      "csv", files
    )
  )

HKG_path <- myfiles %>%
  dplyr::filter(
    grepl(
      HKG, files
    )
  )

gene1_path <- myfiles %>%
  dplyr::filter(
    grepl(
      gene1, files
    )
  )

gene2_path <- myfiles %>%
  dplyr::filter(
    grepl(
      gene2, files
    )
  )

### import and format HKG
names_HKG <- data.frame(matrix(nrow = 0, ncol = 2))
colnames(names_HKG) <- c("Sample", "HKG")

HKG_data <- rbind(
  colnames(names_HKG),
  data.frame(
  Sample = samplenames,
  "HKG" = (read_csv(file = here::here(HKG_path)) %>%
              as.data.frame() %>%
              dplyr::select(
                "Signal"
  ))
)
) 
# there's a clown in the matrix but he has to stay there for now, he's doing important work (this circumvents left_join's annoying default column naming. will make row1 into colnames in next chunk after left_join)

### import and format gene 1
names_gene1 <- data.frame(matrix(nrow = 0, ncol = 2))
colnames(names_gene1) <- c("Sample", "gene1")

gene1_data <- rbind(
  colnames(names_gene1),
  data.frame(
  "Sample" = samplenames,
  "gene1" = (read_csv(file = here::here(gene1_path)) %>%
              as.data.frame() %>%
              dplyr::select(
                "Signal"
  ))
)
)

### import and format gene 2
names_gene2 <- data.frame(matrix(nrow = 0, ncol = 2))
colnames(names_gene2) <- c("Sample", "gene2")

gene2_data <- rbind(
  colnames(names_gene2),
  data.frame(
  "Sample" = samplenames,
  "gene2" = (read_csv(file = here::here(gene2_path)) %>%
              as.data.frame() %>%
              dplyr::select(
                "Signal"
  ))
)
)


# stopifnot(
#   class(HKG_data) == "data.frame" &
#   class(gene1_data) == "data.frame" &
#   class(gene2_data) == "data.frame"
# )
errors <- data.frame(
  numbers = c(1,2,3,4),
  statements = c("did you try turning it off and back on again", "have you tried restarting your computer", "have you updated rstudio recently", "that's rough buddy")
)

if(class(HKG_data) != "data.frame" | class(gene1_data) != "data.frame" | class(gene2_data) != "data.frame") {
  stop(
    dplyr::filter(
  errors, numbers == sample(1:4, 1)
) %>%
  dplyr::select(
    statements
  ) %>%
  as.character()
  )
} else {
  print("qc pass")
}

```

Plan:  
1. build tidy dataframe containing all data
2. divide aSMA coumn and col1A1 column by GAPDH column
3. barplot of results normalized to HKG
3. t test to see if there's significant changes in protein level

```{r de-clownify dataframes and consolidate into tidy df}
tmp <- left_join(
  HKG_data, gene1_data, by = "Sample"
)
tmp <- left_join(
  tmp, gene2_data, by = "Sample"
)
colnames(tmp) <- tmp[1,]
WBQuant <- tmp[2:nrow(tmp),]
rownames(WBQuant) <- WBQuant[,1]
WBQuant <- WBQuant[,2:ncol(WBQuant)]

```

```{r normalize signal and remove remining clowns from the matrix}
WBQuant$GAPDH <- as.numeric(WBQuant$GAPDH)
WBQuant$aSMA <- as.numeric(WBQuant$aSMA)
WBQuant$col1A1 <- as.numeric(WBQuant$col1A1)

WBQuant <- WBQuant %>%
  dplyr::mutate(
    "aSMA" = aSMA / GAPDH,
    "col1A1" = col1A1 / GAPDH,
    .keep = "unused"
  )

WBQuant <- rownames_to_column(WBQuant)

WBQuant_plot <- reshape2::melt(WBQuant)
colnames(WBQuant_plot) <- c("Sample", "Gene", "SignalNorm")
```

```{r calculate significance}
WBQuant_plot$Sample <-WBQuant_plot$Sample %>% 
  gsub(
    pattern = "unstim1|unstim2",
    replacement = "unstim"
  )

WBQuant_plot$Sample <- WBQuant_plot$Sample %>%
  gsub(
    pattern = "stim1|stim2",
    replacement = "stim"
  )

data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
 return(data_sum)
}

data_summary(
  data = WBQuant_plot,
  varname = "tmp",
  groupnames = c("Sample", "Gene","SignalNorm")
)


dplyr::left_join(WBQuant_plot, WBQuant_stats, by = "Sample")
```

```{r ggplot o'clock}
# WBQuant_stats
pQuant <- ggbarplot(WBQuant_plot, 
            x = "Sample", 
            y = "SignalNorm",
            fill = "Gene",
            position = position_dodge(0.8),
            add = c("mean_se", "point")) +
            ggtitle("LM003 WB signals normalized to HKG") +
            facet_grid(cols = vars(Gene), scales = "free_y") +
            theme(legend.position = "none") +
            geom_signif(
              comparisons = list(c("unstim", "stim")),
              map_signif_level = TRUE,
              test = t.test
            )
pQuant


ggsave(
  filename = "LM003_WBQuant.png", plot = pQuant, device = "png", path = here::here("LM003")
)
          
```

```{r statistical tests}
stats <- list()

stats$aSMA_stat$summary <- as.list(
  summary(WBQuant$aSMA)
)

stats$aSMA_stat$Ttest <- t.test(WBQuant$aSMA)


stats$col1A1_stat$summary <- as.list(
  summary(WBQuant$col1A1)
)

stats$col1A1_stat$Ttest <- t.test(WBQuant$col1A1)

```