---
title: "LM003_WBanalysis_blot1"
author: "Libby Murphy"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggthemes)
library(ggpubr)
library(dplyr)
library(here)
library(tidyverse)
library(reshape2)
library(ggsignif)
```

```{r import CSVs clown-style}
# myfilenames <- list.dirs(path = here("LM003", "WBQuants"), full.names = F, recursive = F)

samplenames <- c("unstim", "min5", "min15", "min30", "min60", "min120")


names_ACTB_blot1 <- data.frame(matrix(nrow = 0, ncol = 2))
colnames(names_ACTB_blot1) <- c("Sample", "ACTB_blot1")

ACTB_blot1 <- rbind(
  colnames(names_ACTB_blot1),
  data.frame(  
  "Sample" = samplenames,
  "ACTB" = (read_csv(file = here::here("LM003", "WBQuant", "round2", "ACTB_WBQuant_noP.csv")) %>%
              as.data.frame() %>%
              dplyr::select(
                "Signal"
  ))
)
)

names_ACTB_blot2 <- data.frame(matrix(nrow = 0, ncol = 2))
colnames(names_ACTB_blot2) <- c("Sample", "ACTB_blot2")

ACTB_blot2 <- rbind(
  colnames(names_ACTB_blot2),
  data.frame(  
  "Sample" = samplenames,
  "ACTB" = (read_csv(file = here::here("LM003", "WBQuant", "round2", "ACTB_WBQuant_P.csv")) %>%
              as.data.frame() %>%
              dplyr::select(
                "Signal"
  ))
)
)

names_AKT <- data.frame(matrix(nrow = 0, ncol = 2))
colnames(names_AKT) <- c("Sample", "AKT")

AKT <- rbind(
  colnames(names_AKT),
  data.frame(
  "Sample" = samplenames,
  "AKT" = (read_csv(file = here::here("LM003", "WBQuant", "round2", "AKT_WBQuant_noP.csv")) %>%
              as.data.frame() %>%
              dplyr::select(
                "Signal"
  ))
)
)


names_pAKT <- data.frame(matrix(nrow = 0, ncol = 2))
colnames(names_pAKT) <- c("Sample", "pAKT")


pAKT <- rbind(
  colnames(names_pAKT),
  data.frame(
  "Sample" = samplenames,
  "pAKT" = (read_csv(file = here::here("LM003", "WBQuant", "round2", "pAKT_WBQuant_P.csv")) %>%
              as.data.frame() %>%
              dplyr::select(
                "Signal"
  ))
)
) 

names_p38 <- data.frame(matrix(nrow = 0, ncol = 2))
colnames(names_p38) <- c("Sample", "p38")

p38 <- rbind(
  colnames(names_p38),
  data.frame(
  "Sample" = samplenames,
  "p38" = (read_csv(file = here::here("LM003", "WBQuant", "round2", "p38_WBQuant_noP.csv")) %>%
              as.data.frame() %>%
              dplyr::select(
                "Signal"
  ))
)
)


names_pp38 <- data.frame(matrix(nrow = 0, ncol = 2))
colnames(names_pp38) <- c("Sample", "pp38")


pp38 <- rbind(
  colnames(names_pp38),
  data.frame(
  "Sample" = samplenames,
  "pp38" = (read_csv(file = here::here("LM003", "WBQuant", "round2", "pp38_WBQuant_P.csv")) %>%
              as.data.frame() %>%
              dplyr::select(
                "Signal"
  ))
)
) 


stopifnot(
  class(ACTB_blot1) == "data.frame" &
  class(ACTB_blot2) == "data.frame" &
  class(AKT) == "data.frame" &
  class(pAKT) == "data.frame" &
  class(p38) == "data.frame" &
  class(pp38) == "data.frame"
)

#readxl::read_excel(path = here("LM003", "WBQuants", "LM003_wbQuant_ACTB.xls"), sheet = 1, skip = 1)
```

Plan:  
1. build tidy dataframe containing all data
2. divide SMAD3/ACTB_blot1 and pSMAD/ACTB_blot2
3. divide (pSMAD/ACTB_blot2)/(SMAD3/ACTB_blot1)
4. barplot of results normalized to HKG
5. t test to see if there's significant changes in protein level

```{r de-clownify dataframes and consolidate into tidy df}
tmp <- left_join(
  ACTB_blot1, ACTB_blot2, by = "Sample"
)
tmp <- left_join(
  tmp, AKT, by = "Sample"
)
tmp <- left_join(
  tmp, pAKT, by = "Sample"
)
tmp <- left_join(
  tmp, p38, by = "Sample"
)
tmp <- left_join(
  tmp, pp38, by = "Sample"
)
colnames(tmp) <- tmp[1,]
WBQuant <- tmp[2:nrow(tmp),]
rownames(WBQuant) <- WBQuant[,1]
WBQuant <- WBQuant[,2:ncol(WBQuant)]

```

```{r normalize signal and remove remining clowns from the matrix}
WBQuant$ACTB_blot1  <- as.numeric(WBQuant$ACTB_blot1)
WBQuant$ACTB_blot2  <- as.numeric(WBQuant$ACTB_blot2 )
WBQuant$AKT  <- as.numeric(WBQuant$AKT )
WBQuant$pAKT <- as.numeric(WBQuant$pAKT)
WBQuant$p38  <- as.numeric(WBQuant$p38 )
WBQuant$pp38 <- as.numeric(WBQuant$pp38)

WBQuant <- WBQuant %>%
  dplyr::mutate(
    "AKT" = AKT / ACTB_blot1,
    "pAKT" = pAKT / ACTB_blot2,
    "p38" = p38 / ACTB_blot1,
    "pp38" = pp38 / ACTB_blot2,
    .keep = "unused"
  ) %>%
  dplyr::mutate(
    "norm_AKT" = pAKT / AKT,
    "norm_p38" = pp38 / p38,
    .keep = "used"
  )

WBQuant <- rownames_to_column(WBQuant)

WBQuant_plot <- reshape2::melt(WBQuant)
colnames(WBQuant_plot) <- c("Sample", "Gene", "SignalNorm")

WBQuant_plot$Sample <- WBQuant_plot$Sample %>%
  factor(levels = c("unstim", "min5", "min15", "min30", "min60", "min120"))
```

```{r ggplot o'clock}
# WBQuant_stats
pQuant <- ggbarplot(WBQuant_plot[grep(WBQuant_plot$Gene, pattern = "norm_"),], 
            x = "Sample", 
            y = "SignalNorm",
            fill = "Gene",
            position = position_dodge(0.8),
#            add = c("mean_se", "point")
                ) +
            ggtitle("LM003 TGF-B IMR90 stimulation timecourse: AKT and p38 phosphorylation") +
            facet_wrap(~ Gene, scales = "free_y") +
            theme(legend.position = "none") #+
            # geom_signif(
            #   comparisons = list(c("unstim", "stim")),
            #   map_signif_level = TRUE,
            #   test = t.test
            # )
pQuant


ggsave(
  filename = "LM003_round2_WBQuant.png", plot = pQuant, device = "png", height = 4.5, width = 8, path = here::here("LM003")
)
          
```