---
title: "LM031-2 qPCR analysis"
author: "Libby Murphy"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(here)
library(ggthemes)
require(purrr)
require(reshape2)
library(ggpubr)
library(cowplot)
```

## QC comparisons 

```{r qc, echo=FALSE}
# read in data file 
data <- read_csv(here::here("LM031", "LM031-2_qpcr.csv")) %>% 
  dplyr::select("Target", "Sample", "Cq")

data$Target <- data$Target %>%
  gsub(
    pattern = "Hs_",
    replacement = ""
  )

data$Sample <- data$Sample %>%
  gsub(
    pattern = "CALIB",
    replacement = "NA_NA_CALIB_NA"
  ) %>%
  gsub(
    pattern = "NTC", 
    replacement = "NA_NA_NTC_NA"
  )

```

```{r plot Cq}
data <- separate(data = data, col = Sample, into = c("stim", "alda", "treatment", "rep"), sep = "_", remove = T)

data$Target <- factor(
  data$Target, levels = c("ACTA2", "ALDH2", "COL1A1", "CTGF", "FN", "SERPINE1", "PPIA")
)

data$stim <- factor(
  data$stim, levels = c("TGFB", "unstim", "NA")
)

data$alda <- factor(
  data$alda, levels = c("Alda40", "Alda20", "DMSO", "NA")
)

data$treatment <- factor(
  data$treatment, levels = c("pretx", "conc", "CALIB", "NTC")
)

Cq_QC <- ggplot(data = (data %>% dplyr::filter(treatment != "CALIB")), aes(y = Cq, x = alda, color = treatment, shape = stim)) +
  geom_jitter(width = .2, size = 2) + 
  theme_few() + 
  facet_grid(~Target) +
  ggtitle("Cq LM031-2") +
  theme(axis.text.x = element_text(angle = 60, hjust=1))

Cq_QC

data <- data %>% filter(Cq > 10)

# remove H2ONTC
data_filt <- data %>% filter(treatment != "NTC")
```

```{r normalization, echo=FALSE}
# group data into individual conditions and calculate the condition mean. 
dataSum <- data_filt %>% 
  group_by(Target, stim, alda, treatment, rep) %>%
  dplyr::summarise(Cq = mean(Cq)) %>%
  pivot_wider(names_from = Target, values_from = Cq)

# calculate deltaCq (dCq). Select other targets and subtract HKG from them to get dCq
data_dCq <- bind_cols(
  dataSum %>% dplyr::select(c(stim:rep)),
  dataSum %>% purrr::keep(is.numeric) - dataSum$PPIA
  ) %>% 
  dplyr::select(-"PPIA")

tmp <- data_dCq %>% purrr::keep(is.numeric) %>% t() %>% as.data.frame()

# name columns in object tmp to identify condition
colnames(tmp) <- paste(data_dCq$stim, data_dCq$alda, data_dCq$treatment, data_dCq$rep, sep="_")

# calculate ddCq by subtracting CALIB from other templates
ddCq <- tmp %>% 
  purrr::keep(is.numeric) - tmp$NA_NA_CALIB_NA
ddCq <- ddCq %>%
  dplyr::select(-"NA_NA_CALIB_NA")


ddCq_lfc <- 2^-(ddCq)

ddCq_preplot <- data.frame(t(ddCq_lfc)) %>% 
  rownames_to_column(var = "Sample") 

ddCq_plot <- reshape2::melt(ddCq_preplot, value.name = "Relative_expression_v_PPIA", variable.name = "target") 

ddCq_mean <- ddCq_plot %>%
  separate(
    Sample,
    into = c("stim", "alda", "treatment", "rep"),
    sep = "_"
  )


ddCq_mean$stim <- factor(
  ddCq_mean$stim, levels = c( "NA", "unstim", "TGFB")
)

ddCq_mean$alda <- factor(
  ddCq_mean$alda, levels = c("DMSO", "Alda20", "Alda40", "NA")
)

ddCq_mean$treatment <- factor(
  ddCq_mean$treatment, levels = c("pretx", "conc")
)

ddCq_mean$rep <- factor(
  ddCq_mean$rep, levels = c("rep1", "rep2")
)
```

```{r plotting}
library(ggpattern)

######### instead of the whole situation i did last time, i'm going to adapt this instead:
  # tmp <- as.character(unique(data_norm$sample))
  # tmp <- tmp[c(6,2,4,7,3,5,1,8)]
  test <- unique(data$Target)[c(1:6)] 
  test <- factor(test, levels = c("ACTA2", "ALDH2", "COL1A1", "CTGF", "FN", "SERPINE1"))
  plots <- list()
  prettycolors <- c("OrRd", "OrRd", "Blues", "Blues", "Greens", "Greens", "Reds", "Greys")
  titles <- c("")
  captions <- c("")
  
qwerty <- ddCq_mean[,c(1,2,4,3,5,6)]
qwerty <- qwerty %>% unite("sample", alda:rep, sep = "_", remove = TRUE)
  
for (i in 1:length(test)) {
  plots[[i]] <- (temp <- ggplot(data = qwerty %>% dplyr::filter(target == test[i]), aes(x = sample, y = Relative_expression_v_PPIA, fill = stim, pattern = treatment), position = position_dodge(0.7), width = 0.6) +
  theme_classic() +
#  ylim(0,19)+
geom_col_pattern(position = position_dodge(preserve = "single"),
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  
  scale_fill_brewer(palette = "Pastel1") +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")),
         fill = guide_legend(override.aes = list(pattern = "none"))) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1)) +
  ggtitle(test[i]))
}

cowplot <- cowplot::plot_grid(plotlist = plots, nrow = 2)
cowplot

###########

# ggsave(filename = "LM031-2_plots_QC.png", plot = Cq_QC, device = "png", height = 5, width = 8, path = here::here("LM031"))
# ggsave(filename = "LM031-2_plots.png", plot = cowplot, device = "png", height = 10, width = 12, path = here::here("LM031"), bg = "white")

```
