---
title: "LM031-1 qPCR analysis"
author: "Libby Murphy"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(here)
library(ggthemes)
require(purrr)
require(reshape2)
library(ggpubr)
library(cowplot)
```

## QC comparisons 

```{r qc, echo=FALSE}
# read in data file 
data <- read_csv(here::here("LM031", "LM031_qpcr.csv")) %>% 
  dplyr::select("Target", "Sample", "Cq")

data$Target <- data$Target %>%
  gsub(
    pattern = "Hs_",
    replacement = ""
  )

data$Sample <- data$Sample %>%
  gsub(
    pattern = "CALIB",
    replacement = "NA_NA_NA_CALIB"
  ) %>%
  gsub(
    pattern = "NTC", 
    replacement = "NA_NA_NA_NTC"
  )

```

```{r plot Cq}
data <- separate(data = data, col = Sample, into = c("time", "stim", "alda", "treatment"), sep = "_", remove = T)

data$Target <- factor(
  data$Target, levels = c("COL1A1", "CTGF", "FN", "SERPINE1", "PPIA")
)

data$time <- factor(
  data$time, levels = c("h24", "h48", "h72")
)

data$stim <- factor(
  data$stim, levels = c("TGFb", "unstim", "NA")
)

data$alda <- factor(
  data$alda, levels = c("Alda40", "Alda20", "Alda10", "DMSO", "NA")
)

data$treatment <- factor(
  data$treatment, levels = c("pretx", "conc", "CALIB", "NTC")
)

Cq_QC <- ggplot(data = (data %>% dplyr::filter(treatment != "CALIB") %>% dplyr::filter(time != "NA")), aes(y = Cq, x = time, color = interaction(alda, treatment), shape = stim)) +
  geom_jitter(width = .2, size = 2) + 
  theme_few() + 
  facet_grid(~Target) +
  ggtitle("Cq LM031-1") +
  theme(axis.text.x = element_text(angle = 60, hjust=1))

Cq_QC

data <- data %>% filter(Cq > 10)

# remove H2ONTC
data_filt <- data %>% filter(treatment != "NTC")
```

```{r normalization, echo=FALSE}
# group data into individual conditions and calculate the condition mean. 
dataSum <- data_filt %>% 
  group_by(Target, time, stim, alda, treatment) %>%
  dplyr::summarise(Cq = mean(Cq)) %>%
  pivot_wider(names_from = Target, values_from = Cq)

# calculate deltaCq (dCq). Select other targets and subtract HKG from them to get dCq
data_dCq <- bind_cols(
  dataSum %>% dplyr::select(c(time:treatment)),
  dataSum %>% purrr::keep(is.numeric) - dataSum$PPIA
  ) %>% 
  dplyr::select(-"PPIA")

tmp <- data_dCq %>% purrr::keep(is.numeric) %>% t() %>% as.data.frame()

# name columns in object tmp to identify condition
colnames(tmp) <- paste(data_dCq$time, data_dCq$stim, data_dCq$alda, data_dCq$treatment, sep="_")

# calculate ddCq by subtracting CALIB from other templates
ddCq <- tmp %>% 
  purrr::keep(is.numeric) - tmp$NA_NA_NA_CALIB
ddCq <- ddCq %>%
  dplyr::select(-"NA_NA_NA_CALIB")


ddCq_lfc <- 2^-(ddCq)

ddCq_preplot <- data.frame(t(ddCq_lfc)) %>% 
  rownames_to_column(var = "Sample") 

ddCq_plot <- reshape2::melt(ddCq_preplot, value.name = "Relative_expression_v_PPIA", variable.name = "target") 

ddCq_mean <- ddCq_plot %>%
  separate(
    Sample,
    into = c("time", "stim", "alda", "treatment"),
    sep = "_"
  )

ddCq_mean$time <- factor(
  ddCq_mean$time, levels = c("h24", "h48", "h72")
)

ddCq_mean$stim <- factor(
  ddCq_mean$stim, levels = c( "NA", "unstim", "TGFb")
)

ddCq_mean$alda <- factor(
  ddCq_mean$alda, levels = c("DMSO", "Alda10", "Alda20", "Alda40", "NA")
)

ddCq_mean$treatment <- factor(
  ddCq_mean$treatment, levels = c("pretx", "conc", "CALIB", "NTC")
)
```

```{r plotting}
library(ggpattern)

pCOL1A1_h24 <-  ggplot(data = ddCq_mean %>% dplyr::filter(target == "COL1A1")%>% dplyr::filter(time == "h24"), aes(x = alda, y = Relative_expression_v_PPIA, fill = stim, pattern = treatment), position = position_dodge(0.7), width = 0.6) +
  theme_classic() +
  ylim(0,19)+
geom_col_pattern(position = position_dodge(preserve = "single"),
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  
  scale_fill_brewer(palette = "Pastel1") +
    #  scale_fill_manual(values = colorRampPalette(c("#0066CC","#FFFFFF","#FF8C00"))(4)) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")),
         fill = guide_legend(override.aes = list(pattern = "none"))) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  ggtitle("24 hour treatment")
  
pCOL1A1_h48 <-  ggplot(data = ddCq_mean %>% dplyr::filter(target == "COL1A1")%>% dplyr::filter(time == "h48"), aes(x = alda, y = Relative_expression_v_PPIA, fill = stim, pattern = treatment), position = position_dodge(0.7), width = 0.6) +
  theme_classic() +
  ylim(0,19)+
geom_col_pattern(position = position_dodge(preserve = "single"),
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  
  scale_fill_brewer(palette = "Pastel1") +
    #  scale_fill_manual(values = colorRampPalette(c("#0066CC","#FFFFFF","#FF8C00"))(4)) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")),
         fill = guide_legend(override.aes = list(pattern = "none"))) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  ggtitle("48 hour treatment")

pCOL1A1_h72 <-  ggplot(data = ddCq_mean %>% dplyr::filter(target == "COL1A1")%>% dplyr::filter(time == "h72"), aes(x = alda, y = Relative_expression_v_PPIA, fill = stim, pattern = treatment), position = position_dodge(0.7), width = 0.6) +
  theme_classic() +
  ylim(0,19)+
geom_col_pattern(position = position_dodge(preserve = "single"),
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  
  scale_fill_brewer(palette = "Pastel1") +
    #  scale_fill_manual(values = colorRampPalette(c("#0066CC","#FFFFFF","#FF8C00"))(4)) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")),
         fill = guide_legend(override.aes = list(pattern = "none"))) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  ggtitle("72 hour treatment")



COL1A1plots <- cowplot::plot_grid(pCOL1A1_h24, pCOL1A1_h48, pCOL1A1_h72, nrow = 1)

COL1A1title <- ggdraw() + 
  draw_label(
    "COL1A1",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )
COL1A1plots_labeled <- plot_grid(
  COL1A1title, COL1A1plots,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)

pCTGF_h24 <-  ggplot(data = ddCq_mean %>% dplyr::filter(target == "CTGF")%>% dplyr::filter(time == "h24"), aes(x = alda, y = Relative_expression_v_PPIA, fill = stim, pattern = treatment), position = position_dodge(0.7), width = 0.6) +
  theme_classic() +
  ylim(0,55)+
geom_col_pattern(position = position_dodge(preserve = "single"),
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  
  scale_fill_brewer(palette = "Pastel1") +
    #  scale_fill_manual(values = colorRampPalette(c("#0066CC","#FFFFFF","#FF8C00"))(4)) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")),
         fill = guide_legend(override.aes = list(pattern = "none"))) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  ggtitle("24 hour treatment")
  
pCTGF_h48 <-  ggplot(data = ddCq_mean %>% dplyr::filter(target == "CTGF")%>% dplyr::filter(time == "h48"), aes(x = alda, y = Relative_expression_v_PPIA, fill = stim, pattern = treatment), position = position_dodge(0.7), width = 0.6) +
  theme_classic() +
  ylim(0,55)+
geom_col_pattern(position = position_dodge(preserve = "single"),
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  
  scale_fill_brewer(palette = "Pastel1") +
    #  scale_fill_manual(values = colorRampPalette(c("#0066CC","#FFFFFF","#FF8C00"))(4)) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")),
         fill = guide_legend(override.aes = list(pattern = "none"))) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  ggtitle("48 hour treatment")

pCTGF_h72 <-  ggplot(data = ddCq_mean %>% dplyr::filter(target == "CTGF")%>% dplyr::filter(time == "h72"), aes(x = alda, y = Relative_expression_v_PPIA, fill = stim, pattern = treatment), position = position_dodge(0.7), width = 0.6) +
  theme_classic() +
  ylim(0,55)+
geom_col_pattern(position = position_dodge(preserve = "single"),
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  
  scale_fill_brewer(palette = "Pastel1") +
    #  scale_fill_manual(values = colorRampPalette(c("#0066CC","#FFFFFF","#FF8C00"))(4)) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")),
         fill = guide_legend(override.aes = list(pattern = "none"))) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  ggtitle("72 hour treatment")



CTGFplots <- cowplot::plot_grid(pCTGF_h24, pCTGF_h48, pCTGF_h72, nrow = 1)

CTGFtitle <- ggdraw() + 
  draw_label(
    "CTGF",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )
CTGFplots_labeled <- plot_grid(
  CTGFtitle, CTGFplots,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)


pFN_h24 <-  ggplot(data = ddCq_mean %>% dplyr::filter(target == "FN")%>% dplyr::filter(time == "h24"), aes(x = alda, y = Relative_expression_v_PPIA, fill = stim, pattern = treatment), position = position_dodge(0.7), width = 0.6) +
  theme_classic() +
  ylim(0,18)+
geom_col_pattern(position = position_dodge(preserve = "single"),
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  
  scale_fill_brewer(palette = "Pastel1") +
    #  scale_fill_manual(values = colorRampPalette(c("#0066CC","#FFFFFF","#FF8C00"))(4)) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")),
         fill = guide_legend(override.aes = list(pattern = "none"))) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  ggtitle("24 hour treatment")
  
pFN_h48 <-  ggplot(data = ddCq_mean %>% dplyr::filter(target == "FN")%>% dplyr::filter(time == "h48"), aes(x = alda, y = Relative_expression_v_PPIA, fill = stim, pattern = treatment), position = position_dodge(0.7), width = 0.6) +
  theme_classic() +
  ylim(0,18)+
geom_col_pattern(position = position_dodge(preserve = "single"),
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  
  scale_fill_brewer(palette = "Pastel1") +
    #  scale_fill_manual(values = colorRampPalette(c("#0066CC","#FFFFFF","#FF8C00"))(4)) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")),
         fill = guide_legend(override.aes = list(pattern = "none"))) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  ggtitle("48 hour treatment")

pFN_h72 <-  ggplot(data = ddCq_mean %>% dplyr::filter(target == "FN")%>% dplyr::filter(time == "h72"), aes(x = alda, y = Relative_expression_v_PPIA, fill = stim, pattern = treatment), position = position_dodge(0.7), width = 0.6) +
  theme_classic() +
  ylim(0,18)+
geom_col_pattern(position = position_dodge(preserve = "single"),
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  
  scale_fill_brewer(palette = "Pastel1") +
    #  scale_fill_manual(values = colorRampPalette(c("#0066CC","#FFFFFF","#FF8C00"))(4)) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")),
         fill = guide_legend(override.aes = list(pattern = "none"))) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  ggtitle("72 hour treatment")



FNplots <- cowplot::plot_grid(pFN_h24, pFN_h48, pFN_h72, nrow = 1)

FNtitle <- ggdraw() + 
  draw_label(
    "FN",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )
FNplots_labeled <- plot_grid(
  FNtitle, FNplots,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)

pSERPINE1_h24 <-  ggplot(data = ddCq_mean %>% dplyr::filter(target == "SERPINE1")%>% dplyr::filter(time == "h24"), aes(x = alda, y = Relative_expression_v_PPIA, fill = stim, pattern = treatment), position = position_dodge(0.7), width = 0.6) +
  theme_classic() +
  ylim(0,39)+
geom_col_pattern(position = position_dodge(preserve = "single"),
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  
  scale_fill_brewer(palette = "Pastel1") +
    #  scale_fill_manual(values = colorRampPalette(c("#0066CC","#FFFFFF","#FF8C00"))(4)) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")),
         fill = guide_legend(override.aes = list(pattern = "none"))) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  ggtitle("24 hour treatment")
  
pSERPINE1_h48 <-  ggplot(data = ddCq_mean %>% dplyr::filter(target == "SERPINE1")%>% dplyr::filter(time == "h48"), aes(x = alda, y = Relative_expression_v_PPIA, fill = stim, pattern = treatment), position = position_dodge(0.7), width = 0.6) +
  theme_classic() +
  ylim(0,39)+
geom_col_pattern(position = position_dodge(preserve = "single"),
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  
  scale_fill_brewer(palette = "Pastel1") +
    #  scale_fill_manual(values = colorRampPalette(c("#0066CC","#FFFFFF","#FF8C00"))(4)) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")),
         fill = guide_legend(override.aes = list(pattern = "none"))) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  ggtitle("48 hour treatment")

pSERPINE1_h72 <-  ggplot(data = ddCq_mean %>% dplyr::filter(target == "SERPINE1")%>% dplyr::filter(time == "h72"), aes(x = alda, y = Relative_expression_v_PPIA, fill = stim, pattern = treatment), position = position_dodge(0.7), width = 0.6) +
  theme_classic() +
  ylim(0,39)+
geom_col_pattern(position = position_dodge(preserve = "single"),
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) +
  
  scale_fill_brewer(palette = "Pastel1") +
    #  scale_fill_manual(values = colorRampPalette(c("#0066CC","#FFFFFF","#FF8C00"))(4)) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")),
         fill = guide_legend(override.aes = list(pattern = "none"))) +
  scale_pattern_manual(values = c(pretx = "stripe", conc = "none")) +
  ggtitle("72 hour treatment")



SERPINE1plots <- cowplot::plot_grid(pSERPINE1_h24, pSERPINE1_h48, pSERPINE1_h72, nrow = 1)

SERPINE1title <- ggdraw() + 
  draw_label(
    "SERPINE1",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )
SERPINE1plots_labeled <- plot_grid(
  SERPINE1title, SERPINE1plots,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)

pTooManyPlots <- plot_grid(COL1A1plots_labeled, CTGFplots_labeled, FNplots_labeled, SERPINE1plots_labeled, nrow = 4)
  
# Cq_QC
# pTooManyPlots

ggsave(filename = "LM031-1_plots_QC.png", plot = Cq_QC, device = "png", height = 5, width = 8, path = here::here("LM031"))
ggsave(filename = "LM031-1_plots.png", plot = pTooManyPlots, device = "png", height = 10, width = 12, path = here::here("LM031"), bg = "white")

```
