---
title: "LM047-3_qPCR.csv"
author: "Libby Murphy"
date: "`Sys.Date()"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(tidyverse)
library(here)
library(purrr)
library(conflicted)
conflicts_prefer(dplyr::filter)
library(ggprism)
```

## QC comparisons 

```{r qc, echo=FALSE}
# read in data file 
data <- read_csv(here::here("LM047", "data", "LM047-3_bothplates.csv")) %>% dplyr::select("Well", "Target", "Sample", "Cq")

data$Sample[is.na(data$Sample)] <- "NTC"

Cq_QC <- ggplot(data = data, aes(y = Cq, x = Target, color = Sample)) +
  geom_jitter(width = .2, size = 2) + 
  theme_prism() + 
  ylim(0,40) +
  ggtitle("Cq") +
  theme(axis.text.x = element_text(angle = 60, hjust=1))

data %>% dplyr::filter(Target == "Ppia", Sample == "KO_mock_02")

data <- data[!c(grepl(pattern = "K12", data$Well)),]

data[!is.na(data$Cq),] %>% dplyr::filter(Target == "Gusb", Sample != "CALIB") %>% group_by(Target, Sample) %>% summarise(Cq = mean(Cq)) %>% pull(Cq) %>% sd()
data[!is.na(data$Cq),] %>% dplyr::filter(Target == "Ppia", Sample != "CALIB") %>% group_by(Target, Sample) %>% summarise(Cq = mean(Cq)) %>% pull(Cq) %>% sd() #Ppia wins again

# remove H2ONTC and noRT samples
data_filt <- data %>% filter(Sample != "NTC")

# remove all rows with a Cq of NaN
data_filt <- na.omit(data_filt)
```

```{r normalization, echo=FALSE}
# group data into individual conditions and calculate the condition mean. 
dataSum <- data_filt %>% 
  group_by(Target, Sample) %>%
  dplyr::summarise(Cq = mean(Cq)) %>%
  pivot_wider(names_from = Target, values_from = Cq)

# calculate deltaCq (dCq). Select other targets and subtract Ppia from them to get dCq
data_dCq <- bind_cols(
  dataSum %>% dplyr::select(Sample),
  dataSum %>% purrr::keep(is.numeric) - dataSum$Ppia
  ) %>% 
  dplyr::select(-"Ppia")

tmp <- data_dCq %>% purrr::keep(is.numeric) %>% t()

colnames(tmp) <- data_dCq$Sample

ddCq <- tmp %>%
  as_tibble() %>%
  mutate(KO_TGFb_01 = KO_TGFb_01 - CALIB) %>%
  mutate(KO_TGFb_02 = KO_TGFb_02 - CALIB) %>%
  mutate(KO_mock_01 = KO_mock_01 - CALIB) %>%
  mutate(KO_mock_02 = KO_mock_02 - CALIB) %>%
  mutate(WT_TGFb_01 = WT_TGFb_01 - CALIB) %>%
  mutate(WT_TGFb_02 = WT_TGFb_02 - CALIB) %>%
  mutate(WT_mock_01 = WT_mock_01 - CALIB) %>%
  mutate(WT_mock_02 = WT_mock_02 - CALIB) %>%
  select(-CALIB)

ddCq_lfc <- 2^-(ddCq)

ddCq_preplot <- data.frame(t(ddCq_lfc)) %>% rownames_to_column(var = "Sample") 

colnames(ddCq_preplot)[2:7] <- rownames(tmp)

ddCq_plot <- reshape2::melt(ddCq_preplot, value.name = "ddCq", variable.name = "target") %>% dplyr::filter(target != "Gusb")

ddCq_plot$Sample <- ddCq_plot$Sample %>% gsub(pattern = "_01", replacement = "") %>% gsub(pattern = "_02", replacement = "") 
ddCq_plot <- ddCq_plot %>% group_by(Sample, target) %>% summarise(ddCq = mean(ddCq))
ddCq_plot <- ddCq_plot %>% separate(col = Sample, into = c("genotype", "stim"), remove = TRUE)
```

```{r plotting}
ddCq_plot$genotype <- factor(ddCq_plot$genotype, levels = c("WT", "KO"))
ddCq_plot$stim <- factor(ddCq_plot$stim, levels = c("mock", "TGFb"))

pddCq <- ggplot(ddCq_plot) +
  geom_col(aes(x = target, y = ddCq, fill = stim), color = "black", position = position_dodge()) +
  theme_prism() +
  facet_grid(~genotype) +
  scale_fill_manual(values = c("grey25", "grey75")) +
  theme(axis.text.x = element_text(angle = 60, hjust=0.5)) +
  ggtitle("LM047-3 qPCR: MLF WT vs ALDH2 -/-")

pddCq

Cq_QC

write_csv(ddCq_plot, file = here("LM047", "results", "LM047-3_qpcr_lfc.csv"))

ggsave(filename = "LM047-3_qPCR_lfc.png", plot = pddCq, device = "png", path = here::here("LM047", "results"))

ggsave(filename = "LM047-3_qPCR_Cq.png", plot = Cq_QC, device = "png", path = here::here("LM047", "results"))

ggsave(filename = "LM047-3_qPCR.png", plot = cowplot::plot_grid(Cq_QC, pddCq, nrow = 1), device = "png", height = 5, width = 12, path = here::here("LM047", "results"))
```