---
title: "LM013_collagen"
author: "Libby Murphy"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup}
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(dplyr)
library(here)
library(tidyverse)
library(reshape2)
library(ggsignif)
library(sjmisc)
library(cowplot)
```

```{r import csvs}
myfiles <- data.frame(
  files = list.files(path = here::here("LM013"), full.names = TRUE, recursive = TRUE, all.files = FALSE)
) %>%
  dplyr::filter(
    grepl(
      "csv", files
      ) )

samplenames <- c("scramble_mock1", "scramble_mock2", "scramble_TGFB1", "scramble_TGFB2", "siALDH2_mock1", "siALDH2_mock2", "siALDH2_TGFB1", "siALDH2_TGFB2")

area_0h <-  data.frame(
  "Sample" = samplenames,
  "0h" = (read_csv(file = as.character(myfiles %>% filter(grepl("0h", files)))) %>%
              as.data.frame() %>%
              dplyr::select(
                "Area"
  ))
)

area_24h <-  data.frame(
  "Sample" = samplenames,
  "0h" = (read_csv(file = as.character(myfiles %>% filter(grepl("24h", files)))) %>%
              as.data.frame() %>%
              dplyr::select(
                "Area"
  ))
)

area_48h <-  data.frame(
  "Sample" = samplenames,
  "0h" = (read_csv(file = as.character(myfiles %>% filter(grepl("48h", files)))) %>%
              as.data.frame() %>%
              dplyr::select(
                "Area"
  ))
)

```

```{r calculate contraction}
area <- left_join(
  area_0h, area_24h, by = "Sample"
) %>%
  left_join(
    area_48h, by = "Sample"
  )


colnames(area) <- c("Sample", "Area_0h", "Area_24h", "Area_48h")

area_norm <- area %>%
  dplyr::mutate(
  "h24" = Area_24h / Area_0h,
  "h48" = Area_48h / Area_0h,
  .keep = "unused"
  )

area_norm$Sample <- area_norm$Sample %>%
  gsub(
    pattern = "1|2|3|4",
    replacement = ""
  )

# area_norm <- area_norm %>%
#   group_by(Sample) %>%
#   dplyr::summarise(mean24h = mean(h24), mean48h = mean(h48), mean72h = mean(h72))

area_norm <- reshape2::melt(area_norm)

colnames(area_norm) <- c("Stim", "Time", "AreaNorm")

area_norm <- separate(data = area_norm, col = Stim, into = c("siRNA", "Stim"), sep = "_")
```

```{r ggplot o'clock}
pLM013 <- ggbarplot(area_norm, 
           x = "Time", 
           y = "AreaNorm",
           fill = "Stim",
           position = position_dodge(0.8),
           add = c("mean_se", "point")
           ) +
           geom_signif(
            comparisons = list(c("mock", "TGFB")),
            map_signif_level = TRUE,
            test = t.test
           ) +
           facet_grid(. ~ siRNA) +
           scale_fill_manual(values = lacroix_palette("Lime", type = "discrete", n = 2)) +
           ylim(0,1)
  

ggsave(plot = pLM013, filename = "LM013new_plot.png", device = "png", path = here::here("LM013"))
```