---
title: "LM027-6_analysis"
author: "Libby Murphy"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup}
library(here)
library(tidyverse)
library(readr)
library(purrr)
library(ggpubr)
```

```{r read in and format data}
data <- readr::read_csv(file = here("LM027", "LM027-6_OD450.csv"), locale=locale(encoding="latin1"))

data <- data[,3:length(colnames(data))]

samplenames <- c("ratmito_max_oldkit", "ratmito_max_newkit", "ratmito_max_replkit", "ratmito_mid_oldkit", "ratmito_mid_newkit", "ratmito_mid_replkit", "ratmito_min_oldkit", "ratmito_min_newkit", "ratmito_min_replkit", "HuLung_DF1_oldkit", "HuLung_DF1_newkit", "HuLung_DF1_replkit", "HuLung_DF4_oldkit", "HuLung_DF4_newkit", "HuLung_DF4_replkit", "MsLung_DF1_oldkit", "MsLung_DF1_newkit", "MsLung_DF1_replkit", "MsLung_DF4_oldkit", "MsLung_DF4_newkit", "MsLung_DF4_replkit", "blank_NA_oldkit", "blank_NA_newkit", "blank_NA_replkit")

stopifnot(length(colnames(data)) == length(samplenames))

colnames(data) <- samplenames

# old kit first
data_oldkit <- data %>%
  dplyr::select(grep(pattern = "oldkit", colnames(data)))

data_oldkit_norm <- (data_oldkit %>% purrr::keep(is.numeric) - data_oldkit$blank_NA_oldkit) %>% rownames_to_column(var = "Time")

data_oldkit_norm <- data_oldkit_norm %>% dplyr::select(!grep(pattern = "blank", colnames(data_oldkit_norm)))

# new kit
data_newkit <- data %>%
  dplyr::select(grep(pattern = "newkit", colnames(data)))

data_newkit_norm <- (data_newkit %>% purrr::keep(is.numeric) - data_newkit$blank_NA_newkit) %>% rownames_to_column(var = "Time")

data_newkit_norm <- data_newkit_norm %>% dplyr::select(!grep(pattern = "blank", colnames(data_newkit_norm)))

# repl kit
data_replkit <- data %>%
  dplyr::select(grep(pattern = "replkit", colnames(data)))

data_replkit_norm <- (data_replkit %>% purrr::keep(is.numeric) - data_replkit$blank_NA_replkit) %>% rownames_to_column(var = "Time")

data_replkit_norm <- data_replkit_norm %>% dplyr::select(!grep(pattern = "blank", colnames(data_replkit_norm)))

# join
data_norm <- left_join(data_oldkit_norm, data_newkit_norm, by = "Time")
data_norm <- left_join(data_norm, data_replkit_norm, by = "Time")

data_norm <- pivot_longer(data_norm, 
                          cols = ratmito_max_oldkit:MsLung_DF4_replkit, 
                          names_to = "sample")
data_norm <- data_norm %>% 
  separate(col = sample,
           into = c("sample", "DF", "kit"))
```

```{r stuff and things}
tmp <- as.character(c(1:122))

data_norm$Time <- factor(data_norm$Time, levels = tmp)
data_norm$DF <- factor(data_norm$DF, levels = c("max", "mid", "min", "DF1", "DF4"))

colnames(data_norm)[5] <- "OD450_norm"

data_norm <- data_norm %>%
  dplyr::filter(sample != "buffer")

pMessyplot <- data_norm %>%
  ggplot() +
  geom_line(aes(x=Time, y=OD450_norm, linetype = kit, color = DF, group = interaction(sample, DF, kit)), linewidth = 1) +
  theme_classic() +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank()) +
  ggtitle("LM027-6 ALDH2 activity assay: rat mito, hu lung, ms lung lysates") +
  labs(caption = "ALDH2 activity assay was performed with samples of rat mitochondrial extract, human lung lysate, and mouse lung lysate.")

pRatmito <- (data_norm[grep(pattern = "ratmito", data_norm$sample),]) %>%
  ggplot() +
  ylim(0,0.23) +
  geom_line(aes(x=Time, y=OD450_norm, linetype = DF, color = kit, group = interaction(DF, kit)), linewidth = 1.25) +
  theme_classic() +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank()) +
  ggtitle("LM027-6 ALDH2 activity assay: rat mitocondrial extract") +
  labs(caption = "ALDH2 activity assay was performed with samples of rat mitochondrial extract.")

pHuLung <- (data_norm[grep(pattern = "HuLung", data_norm$sample),]) %>%
  ggplot() +
  ylim(0,0.23) +
  geom_line(aes(x=Time, y=OD450_norm, linetype = DF, color = kit, group = interaction(DF, kit)), linewidth = 1.25) +
  theme_classic() +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank()) +
  ggtitle("LM027-6 ALDH2 activity assay: human lung lysate") +
  labs(caption = "ALDH2 activity assay was performed with samples of human lung lysate.")

pMsLung <- (data_norm[grep(pattern = "MsLung", data_norm$sample),]) %>%
  ggplot() +
  ylim(0,0.23) +
  geom_line(aes(x=Time, y=OD450_norm, linetype = DF, color = kit, group = interaction(DF, kit)), linewidth = 1.25) +
  theme_classic() +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank()) +
  ggtitle("LM027-6 ALDH2 activity assay: mouse lung lysate") +
  labs(caption = "ALDH2 activity assay was performed with samples of mouse lung lysate.")

plots <- c(pRatmito, pHuLung, pMsLung)

cowplot <- cowplot::plot_grid(pRatmito, pHuLung, pMsLung, nrow = 1)

cowplot

ggsave(plot = cowplot, filename = here("LM027", "LM027-6_plot.png"), device = "png", height = 8, width = 20)

```